### ISSUE TITLE
The repository should be moved to Vitis-AWS-F1-Developer-Labs

### ISSUE THREAD

**Issue by rodrigomelo9** [Xilinx/Vitis-AWS-F1-Developer-Labs#54]
Hi. It is still available only at https://github.com/Xilinx/SDAccel-AWS-F1-Developer-Labs/issues/new, but there are instructions such as `git clone https://github.com/Xilinx/Vitis-AWS-F1-Developer-Labs.git Vitis-AWS-F1-Developer-Labs`, which obviously will fail.

Regards,
Rodrigo

**Comment by ThomasXilinx** [comment]
Hi Rodrigo, the repo has now be renamed. Thanks for flagging this.
